# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosAnalyticsTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosAnalyticsTest
pod 'CleverTap-iOS-SDK' 

  target 'iosAnalyticsTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosAnalyticsTestUITests' do
    # Pods for testing
  end

end
